services:
  registry:
    container_name: registry
    ports:
      - "5000:5000"
    extends:
      file: compose.common.yaml
      service: registry

  registry-ui:
    container_name: registry-ui
    ports:
      - "8080:80"
    links:
      - "registry:registry"
    depends_on:
      - registry
    extends:
      file: compose.common.yaml
      service: registry-ui

volumes:
  registry:
