services:
  registry-ui:
    container_name: registry-ui-mephir-io
    image: joxit/docker-registry-ui:main
    restart: always
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    links:
      - "registry:registry"
    labels:
      - "traefik.http.routers.https-registry-ui-mephir-io.rule=Host(`registry.mephir.io`) && PathPrefix(`/ui`)"
      - traefik.http.routers.https-registry-ui-mephir-io.entrypoints=https
      - traefik.http.routers.https-registry-ui-mephir-io.tls=true
      - traefik.http.routers.https-registry-ui-mephir-io.tls.certresolver=cloudflare
      - traefik.http.routers.https-registry-ui-mephir-io.middlewares=stripprefix-ui

      - "traefik.http.middlewares.stripprefix-ui.stripprefix.prefixes=/ui"

      - traefik.enable=true
    networks:
      - traefik

  registry:
    container_name: registry-mephir-io
    image: registry:2
    restart: always
    env_file:
      - path: "./.env"
        required: true
      - path: "./.env.override"
        required: false
    volumes:
      - registry:/data
      - ./auth:/auth
    labels:
      - traefik.http.routers.http-registry-mephir-io.rule=Host(`registry.mephir.io`)
      - traefik.http.routers.http-registry-mephir-io.entrypoints=http
      - traefik.http.routers.http-registry-mephir-io.middlewares=registry-mephir-io-to-https

      - traefik.http.routers.https-registry-mephir-io.rule=Host(`registry.mephir.io`)
      - traefik.http.routers.https-registry-mephir-io.entrypoints=https
      - traefik.http.routers.https-registry-mephir-io.tls=true
      - traefik.http.routers.https-registry-mephir-io.tls.certresolver=cloudflare

      - traefik.http.middlewares.registry-mephir-io-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.registry-mephir-io-to-https.redirectscheme.permanent=true
      - traefik.enable=true
    networks:
      - traefik

volumes:
  registry:

networks:
  traefik:
    external: true
