version: '3'

services:
  registry:
    image: registry:2
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry:/data
    labels:
      - traefik.http.routers.registry.rule=Host(`registry.mephir.io`)

volumes:
  registry:
